name: MGSplegg
main: com.comze_instancelabs.mgsplegg.Main
version: 1.1.3
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   sp:
      description: Main command
      usage: /sp [action]
      aliases: [splegg, mgsplegg, spl]
